import './styles.css';
import {loadCatalogue,readSaved,save} from '../../explorer-data.mjs';
import {kinds,farmPlaces} from '../../explorer-model.mjs';
import {el,heading,button,input,select,itemSummary,inspect,notify,copyLink,download,importFile,safeSave} from '../../explorer-ui.mjs';
export async function setupCollection(){
 const panel=document.getElementById('collection-panel'),data=await loadCatalogue(),valid=new Set(data.items.map(i=>i.slug));panel.replaceChildren();panel.classList.add('tool-page','modern-tools');
 heading(panel,'装备收藏','收藏品','记录已收集的装备，把想要的物品加入心愿清单。');
 const stored=readSaved('collection',{owned:[],wanted:[]});let owned=new Set((Array.isArray(stored.owned)?stored.owned:[]).filter(s=>valid.has(s))),wanted=new Set((Array.isArray(stored.wanted)?stored.wanted:[]).filter(s=>valid.has(s))),kind='all',page=0,onlyWanted=false;
 const persist=()=>safeSave(()=>save('collection',{version:1,owned:[...owned],wanted:[...wanted]}));
 const progress=el('div','tool-progress'),toolbar=el('div','tool-toolbar'),search=input('search','搜索装备名称、套装…'),category=select([['all','所有类别'],['weapon','武器'],...Object.entries(kinds)],kind,v=>{kind=v;page=0;render();}),status=select([['all','全部状态'],['missing','尚未收集'],['owned','已收集'],['wanted','心愿清单']],'all',()=>{page=0;render();});search.setAttribute('aria-label','搜索收藏品');category.setAttribute('aria-label','收藏类别');status.setAttribute('aria-label','收藏状态');
 toolbar.append(search,category,status);const actions=el('div','tool-action-row');actions.append(button('分享心愿清单',()=>copyLink('collection&'+new URLSearchParams({want:[...wanted].join(',')}))),button('导出记录',()=>download('地下城收藏备份.json',{type:'dungeons-collection',version:1,owned:[...owned],wanted:[...wanted]})),button('导入记录',()=>importFile(file=>{
  if(file.type!=='dungeons-collection'||file.version!==1||!Array.isArray(file.owned)||!Array.isArray(file.wanted)||[...file.owned,...file.wanted].some(s=>!valid.has(s)))throw Error();
  owned=new Set(file.owned);wanted=new Set(file.wanted);persist();render();notify('收藏记录已导入');
 })));const caption=el('p','tool-note'),grid=el('div','tool-grid'),pagination=el('div','tool-pages'),farm=el('section','tool-card tool-farm'),farmTop=el('div','tool-action-row'),farmTitle=el('h3','','去哪刷取'),farmToggle=button('仅看心愿清单',()=>{onlyWanted=!onlyWanted;renderFarm();});farmToggle.setAttribute('aria-pressed','false');farmTop.append(farmTitle,farmToggle);const farmList=el('div','tool-farm-list');farm.append(farmTop,el('p','tool-note','按尚未收集的物品数量排序；选择地区可直接定位地图或查看灵魂风暴时间。'),farmList);
 panel.append(progress,toolbar,actions,caption,grid,pagination,farm,el('p','tool-note','收集与心愿清单保存在当前浏览器。导出记录可迁移到另一台设备。'));
 function renderFarm(){farmToggle.setAttribute('aria-pressed',String(onlyWanted));const places=farmPlaces(data.items,owned,wanted,{onlyWanted});farmList.replaceChildren(...places.slice(0,9).map(place=>{const card=el('article','tool-farm-entry');card.append(el('h4','',place.name),el('p','tool-positive',place.items.length+' 件尚未收集'),el('p','meta',place.items.slice(0,4).map(i=>i.name).join('、')+(place.items.length>4?'…':'')));if(place.area){const a=el('a','','地图位置 →');a.href='#'+new URLSearchParams({map:['峡谷','深暗之域','余烬峭壁'].includes(place.area)?'sift':'overworld',area:place.area});card.append(a);if(['咆哮树林','吟唱者草甸','多雨平原','轰鸣虫壳地','安眠丘陵','冰封高地','蜜脾原野'].includes(place.area)){const storm=el('a','','风暴时间');storm.href='#storm&'+new URLSearchParams({region:place.area});card.append(storm);}}return card;}));if(!places.length)farmList.append(el('p','meta',onlyWanted?'心愿清单中的物品已收齐，或还未添加心愿。':'全部物品已收齐。'));}
 function render(){progress.replaceChildren(...[['weapon','武器'],['armor','盔甲'],['artifact','法器'],['talisman','护身符']].map(([id,name])=>{const all=data.items.filter(i=>id==='weapon'?['melee','ranged'].includes(i.kind):i.kind===id),count=all.filter(i=>owned.has(i.slug)).length,b=button('',()=>{kind=kind===id?'all':id;category.value=kind;page=0;render();},'tool-progress-card');b.setAttribute('aria-pressed',String(kind===id));const track=el('span','tool-progress-track'),bar=el('i');bar.style.width=(count/all.length*100)+'%';track.append(bar);b.append(el('span','meta',name),track,el('strong','',count+' / '+all.length));return b;}));
  const q=search.value.trim().toLowerCase(),items=data.items.filter(i=>(kind==='all'||i.kind===kind||kind==='weapon'&&['melee','ranged'].includes(i.kind))&&[i.name,i.english,i.set,i.archetype].join(' ').toLowerCase().includes(q)&&(status.value==='all'||status.value==='missing'&&!owned.has(i.slug)||status.value==='owned'&&owned.has(i.slug)||status.value==='wanted'&&wanted.has(i.slug))).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));
  const totalPages=Math.max(1,Math.ceil(items.length/48));page=Math.min(page,totalPages-1);caption.textContent=`已收集 ${owned.size} / ${data.items.length} · 心愿 ${wanted.size} 件 · 当前筛选 ${items.length} 件`;
  progress.dataset.total=owned.size+' / '+data.items.length;grid.dataset.count=items.length;
  grid.replaceChildren(...items.slice(page*48,page*48+48).map(item=>{const card=el('article','tool-card');card.dataset.owned=String(owned.has(item.slug));card.dataset.item=item.slug;card.dataset.unique=String(item.unique);const details=button('',()=>inspect(item),'tool-item-name');details.append(itemSummary(item));details.setAttribute('aria-label','查看'+item.name+'详情');const row=el('div','tool-card-actions'),label=el('label','tool-owned'),check=input('checkbox','');check.checked=owned.has(item.slug);check.addEventListener('change',()=>{check.checked?owned.add(item.slug):owned.delete(item.slug);persist();render();});label.append(check,el('span','','已收集'));const star=button(wanted.has(item.slug)?'★':'☆',()=>{wanted.has(item.slug)?wanted.delete(item.slug):wanted.add(item.slug);persist();render();},'tool-star');star.setAttribute('aria-label','将'+item.name+'加入心愿清单');star.setAttribute('aria-pressed',String(wanted.has(item.slug)));row.append(label,star);card.append(details,row);return card;}));if(!items.length)grid.append(el('p','tool-empty','没有匹配的物品，试试其他筛选。'));
  const prev=button('上一页',()=>{page--;render();}),next=button('下一页',()=>{page++;render();});prev.disabled=page===0;next.disabled=page===totalPages-1;pagination.replaceChildren(prev,el('span','',`${page+1} / ${totalPages}`),next);renderFarm();
 }
 search.addEventListener('input',()=>{page=0;render();});
 return {show(params){const shared=params.get('want');if(shared!==null){const values=shared.split(',').filter(s=>valid.has(s));wanted=new Set(values);status.value='wanted';notify('已显示链接中的心愿清单；点击星标后会保存到本机。');}render();}};
}
