import './styles.css';
import {navigationGuard} from '../../core/navigation.mjs';
import {loadCatalogue,loadPublicBuilds,loadRules,loadLoadouts,readSaved,save} from '../../explorer-data.mjs';
import {context,decodeBuild,encodeBuild} from '../../explorer-model.mjs';
import {el,heading,button,input,select,itemPicture,modal,inspect,notify,download,importFile,safeSave} from '../../explorer-ui.mjs';
export async function setupBuilds(){
 const [catalogue,publicData]=await Promise.all([loadCatalogue(),loadPublicBuilds()]),items=new Map(catalogue.items.map(i=>[i.slug,i])),panel=document.getElementById('builds-panel');panel.replaceChildren();panel.classList.add('tool-page','modern-tools');
 heading(panel,'配装方案','配装列表','浏览参考配装，或整理自己保存的搭配。选择一套即可载入规划器继续调整。');
 let page=0,records=[],favourites=new Set(),filter='public';const toolbar=el('div','tool-toolbar'),search=input('search','搜索装备、配装名称或标签…'),source=select([['public','参考配装'],['local','我的配装'],['favourites','已收藏配装']],'public',v=>{filter=v;page=0;render();}),style=select([['all','全部战斗方式'],['近战','近战'],['远程','远程'],['混合','混合']],'all',()=>{page=0;render();}),tag=select([['all','全部标签']],'all',()=>{page=0;render();});search.setAttribute('aria-label','搜索配装');source.setAttribute('aria-label','配装来源');style.setAttribute('aria-label','战斗方式');tag.setAttribute('aria-label','配装标签');toolbar.append(search,source,style,tag);
 const actions=el('div','tool-action-row'),newLink=el('a','tool-button-link','新建配装');newLink.href='#planner';actions.append(newLink,button('导出我的配装',()=>download('地下城配装列表.json',{type:'dungeons-build-library',version:1,builds:records})),button('导入配装列表',()=>importFile(importLibrary)));
 const status=el('p','tool-note'),grid=el('div','tool-build-grid'),pagination=el('div','tool-pages');panel.append(toolbar,actions,status,grid,pagination,el('p','tool-note','参考配装来自 dungeons.tools，配置读取于 2026-10-10。个人配装与收藏保存在当前浏览器。'));
 function all(){return [...publicData.builds.map(b=>({...b,public:true,style:b.tags.find(t=>['近战','远程','混合'].includes(t))||'混合'})),...records.map(b=>({...b,public:false}))];}
 function loadSaved(){const saved=readSaved('builds',[]);records=(Array.isArray(saved)?saved:[]).filter(b=>typeof b.id==='string'&&typeof b.name==='string'&&typeof b.q==='string'&&Array.isArray(b.tags));const stars=readSaved('build-favourites',[]);favourites=new Set(Array.isArray(stars)?stars:[]);const current=tag.value,values=[...new Set(all().flatMap(b=>b.tags))].sort((a,b)=>a.localeCompare(b,'zh-CN'));tag.replaceChildren(...[['all','全部标签'],...values.map(v=>[v,v])].map(([v,name])=>{const o=el('option','',name);o.value=v;return o;}));tag.value=values.includes(current)?current:'all';}
 function gearEntries(build){return [...new URLSearchParams(build.q)].map(([slot,raw])=>({slot,raw,item:items.get(raw.split('.')[0])})).filter(e=>e.item);}
 function equipment(build){return gearEntries(build).map(e=>e.item);}
 function pictureOptions(build,{slot,raw}){const fields=raw.split('.');return {rarity:{c:'common',r:'rare',s:'special',u:'unique'}[fields[1]],level:Number(fields[1])||1,equipment:{ench:fields[2]?{slug:fields[2].split('_')[0],tier:['I','II','III'][Number(fields[2].split('_')[1])-1]}:null,query:build.q,slot}};}
 function title(build){return build.title_zh||build.name;}
 function introduction(build){if(build.intro)return build.intro;if(build.note)return build.note.split('\n')[0];const names=equipment(build).slice(0,3).map(i=>i.name);return '核心搭配：'+names.join('、')+'。查看详情了解完整效果与附魔。';}
 function render(){const q=search.value.trim().toLowerCase(),list=all().filter(b=>(filter==='public'?b.public:filter==='local'?!b.public:favourites.has(b.id))&&(style.value==='all'||b.style===style.value)&&(tag.value==='all'||b.tags.includes(tag.value))&&[b.name,title(b),...(b.tags||[]),...equipment(b).flatMap(i=>[i.name,i.english])].join(' ').toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(list.length/12));page=Math.min(page,pages-1);status.textContent=`参考配装 ${publicData.builds.length} 套 · 我的配装 ${records.length} 套 · 当前筛选 ${list.length} 套`;
  grid.replaceChildren(...list.slice(page*12,page*12+12).map(build=>{const card=el('article','tool-card tool-build-card'),header=el('div','tool-build-header'),star=button(favourites.has(build.id)?'★':'☆',()=>{favourites.has(build.id)?favourites.delete(build.id):favourites.add(build.id);safeSave(()=>save('build-favourites',[...favourites]));render();},'tool-star');star.setAttribute('aria-label','收藏'+title(build));star.setAttribute('aria-pressed',String(favourites.has(build.id)));const titleButton=button(title(build),()=>view(build),'tool-build-title');header.append(titleButton,star);const icons=el('div','tool-build-icons');for(const entry of gearEntries(build)){const item=entry.item,image=itemPicture(item,pictureOptions(build,entry)),slotButton=button('',()=>inspect(item),'tool-gear-button');slotButton.setAttribute('aria-label','查看'+item.name+'详情');slotButton.append(image);icons.append(slotButton);}const chips=el('div','tool-build-tags');for(const text of build.tags.slice(0,6))chips.append(el('span','info-chip',text));const actions=el('div','tool-action-row'),link=el('a','tool-button-link','载入规划器');link.href='#planner&'+build.q+(build.public?'':'&edit='+encodeURIComponent(build.id));actions.append(link,button('查看搭配',()=>view(build)));
   if(!build.public)actions.append(button('删除',()=>remove(build)));
   if(build.public&&Number.isFinite(build.reference_votes)){const votes=el('div','tool-build-rank');votes.append(el('span','','▲'),el('strong','',String(build.reference_votes)),el('span','','参考票数'));votes.title='dungeons.tools 于 2026-10-10 的票数快照';card.append(votes);}card.append(header);if(build.public&&build.author)card.append(el('p','tool-build-original','作者 '+build.author));card.append(chips,el('p','build-introduction',introduction(build)),icons,actions);return card;}));if(!list.length)grid.append(el('p','tool-empty',filter==='local'?'还没有保存配装。在规划器中保存后即可在这里找到。':'没有匹配的配装，试试其他筛选。'));const prev=button('上一页',()=>{page--;render();}),next=button('下一页',()=>{page++;render();});prev.disabled=page===0;next.disabled=page===pages-1;pagination.replaceChildren(prev,el('span','',`${page+1} / ${pages}`),next);
 }
 async function view(build){const current=navigationGuard();try{const {showBuildDetail}=await import('../../build-detail.mjs');if(current())await showBuildDetail(build,title(build),introduction(build));}catch{if(current())notify('配装详情读取失败，请重试。');}}
 function remove(build){const box=modal('删除配装');box.body.append(el('p','tool-description','删除“'+build.name+'”？可以先导出配装列表保留备份。'),button('删除这套配装',()=>{const next=records.filter(b=>b.id!==build.id);if(safeSave(()=>save('builds',next))){records=next;box.close();render();notify('配装已删除');}},''));box.open();box.dialog.addEventListener('close',()=>box.dialog.remove(),{once:true});}
 async function importLibrary(file){if(file.type!=='dungeons-build-library'||file.version!==1||!Array.isArray(file.builds)||file.builds.length>200)throw Error();const [rules,loadouts]=await Promise.all([loadRules(),loadLoadouts()]),ctx=context(catalogue,rules,loadouts),incoming=[];for(const b of file.builds){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>80||typeof b.q!=='string'||b.q.length>10000||!Array.isArray(b.tags)||b.tags.some(t=>typeof t!=='string'||t.length>80)||typeof b.note!=='string'||b.note.length>8000)throw Error();const parsed=decodeBuild(b.q,ctx);if(!Object.keys(parsed).length)throw Error();incoming.push({id:'local-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),name:b.name,style:['近战','远程','混合'].includes(b.style)?b.style:'混合',tags:b.tags.slice(0,8),note:b.note,q:encodeBuild(parsed,ctx),updated:Date.now()});}if(!safeSave(()=>save('builds',[...incoming,...records])))return;loadSaved();filter='local';source.value=filter;page=0;render();notify('已导入 '+incoming.length+' 套配装');}
 search.addEventListener('input',()=>{page=0;render();});return {show(params){loadSaved();if(params.get('mine')==='1'){filter='local';source.value=filter;}render();if(params.get('build')){const selected=all().find(b=>b.id===params.get('build'));if(selected)view(selected);}}};
}
