import './styles.css';
import {loadCatalogue,loadRules,loadLoadouts,readSaved,save} from '../../explorer-data.mjs';
import {context,slots,compatible,normalizeBuild,decodeBuild,encodeBuild,effectTotals,rarities} from '../../explorer-model.mjs';
import {el,heading,button,field,input,select,itemPicture,itemSummary,modal,inspect,notify,copyLink,download,importFile,safeSave} from '../../explorer-ui.mjs';
export async function setupPlanner(){
 const [catalogue,rules,loadouts]=await Promise.all([loadCatalogue(),loadRules(),loadLoadouts()]),ctx=context(catalogue,rules,loadouts),panel=document.getElementById('planner-panel');panel.replaceChildren();panel.classList.add('tool-page','modern-tools');
 heading(panel,'自由搭配','配装规划','组合 12 个装备部位，选择随机效果与附魔，查看整套配装的效果。');
 let build={},active='melee',lastQuery='',recordId=null,choosing=false;
 const actions=el('div','tool-action-row'),summary=el('span','meta');actions.append(button('保存配装',saveDialog,''),button('分享配装',()=>copyLink('planner&'+encodeBuild(build,ctx))),button('导出配装',()=>download('地下城配装备份.json',{type:'dungeons-build',version:1,build:normalizeBuild(build,ctx)})),button('导入配装',()=>importFile(file=>{if(file.type!=='dungeons-build'||file.version!==1||!file.build||typeof file.build!=='object')throw Error();const clean=normalizeBuild(file.build,ctx);if(!Object.keys(clean).length||Object.keys(clean).length!==Object.keys(file.build).length)throw Error();build=clean;recordId=null;update();notify('配装已导入');})),button('清空槽位',()=>{build={};recordId=null;update();}),summary);
 const layout=el('div','tool-planner-layout'),screen=el('div','tool-planner-screen'),slotGrid=el('div','tool-slots'),editor=el('section','tool-card tool-editor'),totals=el('section','tool-card tool-totals');screen.append(slotGrid);layout.append(screen,editor,totals);panel.querySelector(".page-heading").append(actions);panel.append(layout);
 function persist(){safeSave(()=>save('draft',build));const query=encodeBuild(build,ctx);lastQuery=query;history.replaceState(null,'','#planner'+(query?'&'+query:''));}
 function update(){build=normalizeBuild(build,ctx);persist();render();}
 function setItem(slot,item){build[slot.id]={item:item.slug,rarity:item.unique?'unique':'special',level:1,rolls:[],ench:null};active=slot.id;choosing=false;update();}
 function openPicker(slot){active=slot.id;choosing=true;render();}
 function render(){const focused=editor.contains(document.activeElement)&&document.activeElement.matches('input,select,textarea')?document.activeElement.getAttribute('aria-label'):null;summary.textContent=`已配置 ${Object.keys(build).length} / 12 · 自动保存`;slotGrid.replaceChildren();
  for(const [group,ids] of [['武器',['melee','ranged']],['盔甲',['helmet','chest','legs','boots']],['法器',['a1','a2','a3']],['护身符',['t1','t2','t3']]]){
   const section=el('section','tool-slot-group');section.append(el('h3','',group));const grid=el('div','tool-slot-row');
   for(const id of ids){const slot=slots.find(s=>s.id===id),entry=build[id],item=ctx.items.get(entry?.item),b=button('',()=>{active=id;choosing=!item;render();if(matchMedia('(max-width:760px)').matches)editor.scrollIntoView({block:'start'});},'tool-slot');b.dataset.slot=id;b.setAttribute('aria-pressed',String(active===id));b.setAttribute('aria-label',slot.name+(item?'：'+item.name:'：选择装备'));b.append(el('span','tool-slot-label',slot.name));if(item){b.append(itemPicture(item,{rarity:entry.rarity,level:entry.level,equipment:entry}),el('strong','',item.name));if(entry.ench)b.append(el('span','tool-slot-enchant',ctx.enchants.get(entry.ench.slug).name+' '+entry.ench.tier));}else b.append(el('span','tool-slot-empty','＋'),el('span','meta','选择装备'));grid.append(b);}
   section.append(grid);slotGrid.append(section);
  }
  renderEditor();renderTotals();if(focused)[...editor.querySelectorAll('input,select,textarea')].find(n=>n.getAttribute('aria-label')===focused)?.focus({preventScroll:true});
 }
 function renderEditor(){const slot=slots.find(s=>s.id===active),entry=build[active],item=ctx.items.get(entry?.item);editor.replaceChildren(el('h3','tool-section-heading',slot.name));if(!item||choosing){const filter=input('search','搜索'+slot.name+'…'),list=el('div','tool-inline-picker');filter.setAttribute('aria-label','筛选'+slot.name);const choices=[...ctx.items.values()].filter(i=>compatible(i,slot));function draw(){const q=filter.value.trim().toLowerCase();list.replaceChildren(...choices.filter(i=>[i.name,i.english].join(' ').toLowerCase().includes(q)).map(i=>{const b=button('',()=>setItem(slot,i),'tool-inline-choice');b.append(itemPicture(i),el('span','',i.name));return b;}));}filter.addEventListener('input',draw);editor.append(filter,list);if(item)editor.append(button('取消更换',()=>{choosing=false;render();}));draw();return;}
  editor.append(itemSummary(item,{rarity:entry.rarity,level:entry.level,equipment:entry}));const row=el('div','tool-action-row');row.append(button('更换装备',()=>openPicker(slot)),button('物品详情',()=>inspect(item,editor.querySelector('.tool-item-picture'))),button('移除',()=>{delete build[active];update();}));editor.append(row);if(item.description&&item.descriptionOrigin!=='native-level-I-effect')editor.append(el('p','tool-description',item.description));
  const form=el('div','tool-form');editor.append(form);
  if(item.kind==='talisman'){
   form.append(field('护身符等级',select([['1','I 级'],['2','II 级'],['3','III 级']],String(entry.level),v=>{entry.level=Number(v);update();})));for(const e of item.levels[entry.level-1].effects)form.append(el('p','tool-description',e.text));return;
  }
  form.append(field('品质',select(Object.entries(rarities).filter(([id])=>item.unique?id==='unique':id!=='unique'),entry.rarity,v=>{entry.rarity=v;update();})),el('p','tool-roll-text','普通、稀有、特殊装备分别有 0、1、2 个随机效果；独特装备另有固有效果。'));
  for(const e of item.fixed){const fixed=el('div','tool-fixed-effect');fixed.append(el('span','meta','固有效果'),el('strong','',ctx.rules.effects[e.effect]?.name||e.name),el('p','',e.text));form.append(fixed);}
  for(let n=0;n<entry.rolls.length;n++){
   const selected=ctx.templates.get(entry.rolls[n]),other=entry.rolls.filter((_,i)=>i!==n).map(t=>ctx.templates.get(t)?.effect),eligible=item.pool.map(t=>ctx.templates.get(t)).filter(t=>!other.includes(t.effect)),effects=[...new Set(eligible.map(t=>t.effect))].sort((a,b)=>rules.effects[a].name.localeCompare(rules.effects[b].name,'zh-CN'));
   const line=el('div','tool-roll-line'),effect=select([['','选择随机效果'],...effects.map(e=>[e,rules.effects[e].name])],selected?.effect||'',v=>{entry.rolls[n]=eligible.find(t=>t.effect===v&&t.tier===(selected?.tier||'III'))?.tag||eligible.find(t=>t.effect===v)?.tag||null;update();}),grade=select([['I','I 级'],['II','II 级'],['III','III 级']],selected?.tier||'III',v=>{entry.rolls[n]=eligible.find(t=>t.effect===selected?.effect&&t.tier===v)?.tag||null;update();});grade.disabled=!selected;
   line.append(field('随机效果 '+(n+1),effect),field('等级',grade));form.append(line);if(selected)form.append(el('p','tool-roll-text',selected.text));
  }
  if(slot.ench){const eligible=rules.enchants.filter(e=>e.slots.includes(slot.ench)),enchant=ctx.enchants.get(entry.ench?.slug),line=el('div','tool-roll-line'),effect=select([['','不使用附魔'],...eligible.map(e=>[e.slug,e.name])],entry.ench?.slug||'',v=>{entry.ench=v?{slug:v,tier:entry.ench?.tier||'III'}:null;update();}),grade=select([['I','I 级'],['II','II 级'],['III','III 级']],entry.ench?.tier||'III',v=>{if(entry.ench){entry.ench.tier=v;update();}});grade.disabled=!enchant;line.append(field('使用附魔',effect),field('等级',grade));form.append(line);
   if(enchant){const line=el('div','tool-chosen-enchant');line.append(itemPicture({...enchant,kind:'enchantment'},{book:true}),el('p','',enchant.tiers.find(t=>t.tier===entry.ench.tier).text));form.append(line);}
  }
 }
 function renderTotals(){const result=effectTotals(build,ctx);totals.replaceChildren(el('h3','tool-section-heading','整套配装效果'));
  if(!result.effects.length&&!result.enchants.length){totals.append(el('p','tool-note','选择装备及效果后，这里会汇总所有贡献。'));return;}
  for(const effect of result.effects){const row=el('details','tool-total-row'),summary=el('summary'),image=effect.info?.image?el('img'):null;if(image){image.src=effect.info.image;image.alt='';image.width=28;image.height=28;summary.append(image);}const content=el('div');content.append(el('strong','',(/[^\x00-\x7F]/.test(effect.info?.name||" ")?effect.info.name:effect.entries[0]?.item||"装备效果")),el('p','',effect.text));summary.append(content,el('span','meta','×'+effect.entries.length));row.append(summary);const sources=el('ul');for(const e of effect.entries)sources.append(el('li','',e.slot+' · '+e.item+'：'+e.text));row.append(sources);totals.append(row);}
  if(result.enchants.length){totals.append(el('h4','tool-enchants-heading','已配置附魔'));for(const enchant of result.enchants){const row=el('div','tool-total-enchant'),info=el('div');info.append(el('strong','',enchant.name+' '+enchant.tier),el('p','meta',enchant.slot),el('p','',enchant.text));row.append(itemPicture({...enchant,kind:'enchantment'},{book:true}),info);totals.append(row);}}
  totals.append(el('p','tool-note','同名随机效果按游戏数值相加；附魔按触发部位分别列出。条件效果的触发率与持续时间保留在详情中。'));
 }
 function saveDialog(){if(!Object.keys(build).length){notify('请先选择至少一件装备');return;}const saved=readSaved('builds',[]),records=Array.isArray(saved)?saved:[],existing=records.find(r=>r.id===recordId),box=modal(existing?'更新配装':'保存配装'),name=input('text','例如：近战连招配装',existing?.name||''),style=select([['近战','近战'],['远程','远程'],['混合','混合']],existing?.style||'近战'),tags=input('text','刷取、首领、合作…',existing?.tags?.join('、')||''),note=el('textarea');name.maxLength=80;tags.maxLength=160;note.maxLength=8000;note.value=existing?.note||'';const form=el('form','tool-form');name.required=true;form.append(field('配装名称',name),field('战斗方式',style),field('标签（用逗号或顿号分隔）',tags),field('搭配说明',note));const submit=el('button','','保存到我的配装');submit.type='submit';form.append(submit);box.body.append(form);box.open();name.focus();
  form.addEventListener('submit',e=>{e.preventDefault();const title=name.value.trim();if(!title){name.focus();return;}const record={id:existing?.id||('local-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)),name:title,style:style.value,tags:tags.value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean).slice(0,8),note:note.value.trim(),q:encodeBuild(build,ctx),updated:Date.now()};const next=[record,...records.filter(r=>r.id!==record.id)];if(safeSave(()=>save('builds',next))){recordId=record.id;box.close();notify('已保存，可在“配装列表”查看');}});box.dialog.addEventListener('close',()=>box.dialog.remove(),{once:true});
 }
 return {show(params){const query=slots.some(s=>params.has(s.id))?params.toString():null;if(query){build=decodeBuild(params,ctx);recordId=params.get('edit')||null;lastQuery=encodeBuild(build,ctx);}else if(!lastQuery)build=normalizeBuild(readSaved('draft',{}),ctx);render();}};
}
