"""Import cooked tooltip material values and unchanged UI art/font from the game.

Usage: python tools/import-native-tooltip-ui.py <full re-extraction directory>
Unreal widgets/material shaders are rendered with browser equivalents; this is
not a screenshot skin. Runtime equipment values remain supplied by the site.
"""
import hashlib
import json
from pathlib import Path
import shutil
import sys
from fontTools.ttLib import TTFont

source = Path(sys.argv[1]).resolve()
repo = Path(__file__).resolve().parents[1]
widget = Path('ui-complete/Dungeons/Plugins/OreUI/Content/UI/Widget')
records = []


def read(relative):
    path = source / relative
    records.append({'source': relative.as_posix(), 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
    return json.loads(path.read_text(encoding='utf-8'))


def instance_colors(relative):
    obj = read(widget / relative)[0]
    return {v['ParameterInfo']['Name']: '#' + v['ParameterValue']['Hex'] for v in obj['Properties']['VectorParameterValues']}


def material_colors(relative):
    obj = read(widget / relative)[0]['CachedExpressionData']
    return {p['Name']: '#' + v['Hex'] for p, v in zip(obj['RuntimeEntries[1]']['ParameterInfoSet'], obj['VectorValues'])}


header = instance_colors(Path('Tooltip/Modules/MI_UI_ToolTipModule_Equipped.json'))
border = material_colors(Path('Panel/TooltipContentPanel/M_UI_Tooltip_Border.json'))
rarity = instance_colors(Path('Tooltip/Modules/MI_RarityUnique_BG.json'))
level = material_colors(Path('Tooltip/Modules/Components/M_EnchantLevelIndicator.json'))
for relative in ['Tooltip/W_Tooltip.json', 'Panel/W_TooltipContentPanel.json',
                 'Tooltip/Modules/W_TooltipModule_Equipped.json', 'Tooltip/Modules/W_TooltipModule_Enchantment.json',
                 'Tooltip/Modules/Components/W_TooltipModule_EffectEntry.json', 'Tooltip/Modules/W_TooltipModule_Rarity.json']:
    read(widget / relative)
read(Path('ui-complete/Dungeons/Content/Fonts/NewFive.json'))
panel=read(widget / 'Panel/W_TooltipContentPanel.json')
inset=next(o for o in panel if o['Name']=='VerticalBoxSlot_1')['Properties']['Padding']['Left']
styles=Path('ui-complete/Dungeons/Plugins/OreUI/Content/UI/Typography/TextStyles')
def font_size(name):
    objects=read(styles / (name+'.json'))
    return next(o for o in objects if o['Name'].startswith('Default__'))['Properties']['Font']['Size']
body_size=font_size('Style_Body_Text')
title_size=font_size('Style_Header4_Text')
section_size=font_size('Style_SectionHeader1_Text')
grade_size=font_size('Custom_Variants/Style_EnchantmentLevelIndicator')

tokens = {
    'header': header['ColorFill'], 'header-edge': header['Color Outer Line'],
    'header-shine': header['Color Outer Line Top'], 'panel': border['Base Color'],
    'panel-shine': border['Shine Color'], 'unique': rarity['TagColor'],
    'level-top': level['Top Color'], 'level-bottom': level['Bottom Color'],
}
css = '/* Generated by tools/import-native-tooltip-ui.py from cooked game materials. */\n'
css += '.equipment-tooltip.native-game-tooltip{\n'
css += ''.join(f' --game-tip-{name}:{value};\n' for name, value in tokens.items())
css += f' --game-native-inset:{inset:g}px;\n --game-native-body:{body_size:g}px;\n --game-native-title:{title_size:g}px;\n --game-native-section:{section_size:g}px;\n --game-native-grade:{grade_size:g}px;\n' + '}\n'
(repo / 'src/ui/styles/game-tooltip-tokens.css').write_text(css, encoding='utf-8')

mask = Path('textures/Dungeons/Plugins/OreUI/Content/UI/Textures/UI_FX/T_UI_Enchant_Icon_Mask.png')
out = repo / 'public/images/native-tooltip/enchant-mask.png'
out.parent.mkdir(parents=True, exist_ok=True)
shutil.copyfile(source / mask, out)
records.append({'source': mask.as_posix(), 'file': out.relative_to(repo / 'public').as_posix(),
                'sha256': hashlib.sha256(out.read_bytes()).hexdigest()})
for name,file in [('T_UI_Icon_Timer','timer'),('T_UI_Icon_Soul_Cost','soul-cost')]:
    relative=Path('textures/Dungeons/Plugins/OreUI/Content/UI/Widget/Tooltip/Modules') / (name+'.png')
    target=out.parent / (file+'.png')
    shutil.copyfile(source / relative,target)
    records.append({'source':relative.as_posix(),'file':target.relative_to(repo / 'public').as_posix(),'sha256':hashlib.sha256(target.read_bytes()).hexdigest()})
relative=Path('textures/Dungeons/Plugins/OreUI/Content/UI/Icons/Currency/T_UI_Icon_EnchantmentSwirl.png')
target=out.parent/'enchantment-swirl.png'
shutil.copyfile(source/relative,target)
records.append({'source':relative.as_posix(),'file':target.relative_to(repo/'public').as_posix(),'sha256':hashlib.sha256(target.read_bytes()).hexdigest()})
font_source = Path('organized/fonts/Dungeons/Content/Fonts/MinecraftFive.otf')
font_path = repo / 'public/fonts/native-five.woff2'
font = TTFont(source / font_source)
font.flavor = 'woff2'
font.save(font_path)
records.append({'source': font_source.as_posix(), 'file': font_path.relative_to(repo / 'public').as_posix(),
                'source_sha256': hashlib.sha256((source / font_source).read_bytes()).hexdigest(),
                'sha256': hashlib.sha256(font_path.read_bytes()).hexdigest()})
font_source=Path('organized/fonts/Dungeons/Content/Spicewood/Fonts/Spicewood/Font_Spicewood_TenV2_Regular.otf')
font_path=repo / 'public/fonts/native-ten.woff2'
font=TTFont(source / font_source);font.flavor='woff2';font.save(font_path)
records.append({'source':font_source.as_posix(),'file':font_path.relative_to(repo / 'public').as_posix(),'source_sha256':hashlib.sha256((source / font_source).read_bytes()).hexdigest(),'sha256':hashlib.sha256(font_path.read_bytes()).hexdigest()})

manifest = {'widget': 'W_Tooltip', 'colors': tokens, 'sources': records,
            'adaptation': {'nativeContentInset': inset, 'webContentInset': inset * .5, 'scale': .5,
                           'nativeModuleSpacing': 32, 'webModuleSpacing': 16,
                           'rendering': 'CSS equivalents for cooked Unreal materials, with original icon textures and Five/Ten fonts.',
                           'equipmentValues': 'Catalogue/build values only; no invented player level or item power.'}}
(repo / 'public/data/native-tooltip-ui.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Imported {len(records)} native UI sources, original icons and Five/Ten fonts.')
